name: Update Entries JSON

on:
  push:
    branches: [ main, master ]
    paths:
      - 'data/**/*.md'
      - 'data/**/'
      - '!data/entries.json'

jobs:
  update-entries:
    runs-on: ubuntu-latest  # Fix typo: was "ubUntu-latest"
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Important to get full git history
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Update entries.json
      run: |
        echo "Checking for changes in data directory..."
        python -c "
        import os
        import json
        from pathlib import Path

        data_dir = 'data'
        entries_file = Path(data_dir) / 'entries.json'

        entries = []
        for entry_dir in sorted(Path(data_dir).iterdir()):
            if entry_dir.is_dir():
                lang_files = [f for f in entry_dir.glob('*.md') if f.is_file()]
                if lang_files:
                    langs = sorted([f.stem for f in lang_files])
                    entry_name = ' '.join(word.capitalize() for word in entry_dir.name.split('_'))
                    entries.append({
                        'name': entry_name,
                        'directory': entry_dir.name,
                        'langs': langs
                    })
                    print(f'Found: {entry_name} ({entry_dir.name}) with langs: {", ".join(langs)}')

        with open(entries_file, 'w') as f:
            json.dump(entries, f, indent=2, ensure_ascii=False)
        print(f'Successfully updated {entries_file} with {len(entries)} entries')
        "
    
    - name: Commit changes if needed
      id: commit
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add data/entries.json
        
        # Only commit if there are changes
        if git diff --quiet --staged; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update entries.json with new languages/disorders"
          echo "changes=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Push changes
      if: steps.commit.outputs.changes == 'true'
      run: git push
